config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
      get '/admin/login' => 'devise/sessions#new'
      post '/admin/logout' => 'devise/sessions#create'
      delete '/admin/logout' => 'devise/sessions#destroy'
  end

  get 'speakers/show'

  get 'admin/index'

  root 'static#index'
  get '/about', to: 'static#about', as: 'about'
  get '/agenda', to: 'static#agenda', as: 'agenda'
  get '/sponsors', to: 'static#sponsors', as: 'sponsors'

  authenticate :user do
      get '/admin/', to: 'admin#index', as: 'admin_root'
      get '/admin/site_options', to: 'admin#site_options', as: 'admin_site_options'
      get '/admin/view/speakers', to: 'admin#show_speakers', as: 'admin_show_speakers'
      get '/admin/edit/speaker/:slug', to: 'admin#edit_speaker', as: 'admin_edit_speaker'
      get '/admin/add/speaker', to: 'admin#new_speaker', as: 'admin_new_speaker'
      get '/admin/api/slug_check', to: 'admin#slug_check', as: 'admin_slug_check'
      post '/admin/update/speaker', to: 'admin#update_speaker', as: 'admin_update_speaker'
      post '/admin/add/speaker', to: 'admin#create_speaker', as: 'admin_create_speaker'
      delete '/admin/delete/speaker/:slug', to: 'admin#delete_speaker', as: 'admin_delete_speaker'
  end


  get '/speaker/:slug', to: 'speakers#show', as: 'show_speaker'

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base

    has_attached_file :pic, styles: {
        :original => '300x450#'
    }

    validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout 'admin'

    def index

    end

    def site_options

    end

    def show_speakers
        @speakers = Speaker.all
    end

    def new_speaker

    end

    def create_speaker
        @speaker = Speaker.create(speaker_params)

        if @speaker.valid?
            flash[:success] = 'Successfully created a new speaker'
            redirect_to(admin_show_speakers_path)
        else
            flash[:error] = @speaker.errors
            redirect_to(admin_new_speaker_path)
        end
    end

    def edit_speaker
        @speaker = Speaker.where(slug: params[:slug]).first
    end

    def update_speaker
        @speaker = Speaker.find(params[:speaker_id])
        if @speaker.update_attributes(speaker_params)
            redirect_to(admin_show_speakers_path)
        else
            redirect_to(admin_edit_speaker_path, slug: @speaker.slug)
        end
    end

    def delete_speaker
        Speaker.where(slug: params[:slug]).destroy_all
        redirect_to(admin_show_speakers_path)
    end

    def slug_check
        @speaker = Speaker.where(slug: params[:slug]).first
    end



    def speaker_params
        params.require(:speaker).permit(:name, :title, :slug, :bio, :pic, :facebook_url, :twitter_url, :linkedin_url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def show
    @nav_with_bg = true
    @speaker = Speaker.where(slug: params[:slug]).first
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
      @speakers = Speaker.all
      @prices = [
          {
              price: '$199',
              date: '11/21/2015'
          },
          {
              price: '$299',
              date: '12/21/2015'
          },
          {
              price: '$399',
              date: '01/21/2016'
          },
          {
              price: '$499',
              date: '01/27/2016'
          }
      ]

  end
  def about

  end
  def agenda
    @nav_with_bg = true
  end
  def sponsors

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def markdown(text)
        options = {
            filter_html:     true,
            hard_wrap:       true,
            link_attributes: { rel: 'nofollow', target: "_blank" },
            space_after_headers: true,
            fenced_code_blocks: true
        }

        extensions = {
            autolink:           true,
            superscript:        true,
            disable_indented_code_blocks: true
        }

        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)

        markdown.render(text).html_safe
    end

end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/admin/edit_speaker.html.erb
<div id="new-speaker">
  <div class="container">
	<h1 class="section-title">Edit Speaker</h1>

	<form action="<%= admin_update_speaker_url %>" method="post" class="new-speaker-form" enctype="multipart/form-data">

	  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	  <%= hidden_field_tag :speaker_id, @speaker.id %>

	  <fieldset class="form-group">
		<label class="control-label" for="name">Name</label>
		<input name="speaker[name]" type="text" id="name" class="form-control" value="<%= @speaker.name %>">
	  </fieldset>

	  <fieldset class="form-group">
		<label class="control-label" for="name">Title</label>
		<input name="speaker[title]" type="text" id="title" class="form-control" value="<%= @speaker.title %>">
	  </fieldset>

	  <fieldset class="form-group">
		<label class="control-label" for="slug">Slug</label>
		<input name="speaker[slug]" type="text" id="slug" class="form-control" placeholder="e.g. john_doe" value="<%= @speaker.slug %>">
		<small class="text-muted">This will be for the pretty URL. The speaker's profile will be at <b>/speaker/slug_here</b>.</small>
	  </fieldset>

	  <fieldset class="form-group">
		<label class="control-label" for="bio">Bio</label>
		<textarea name="speaker[bio]" id="bio" cols="30" rows="10" class="form-control"><%= @speaker.bio %></textarea>
		<small class="text-muted">You can use <a href="https://help.github.com/articles/markdown-basics/">markdown</a> here.</small>
	  </fieldset>

	  <fieldset class="form-group">
		<label class="control-label" for="profile-pic">Profile picture</label>
		<input type="file" class="form-control-file" name="speaker[pic]" value="<%= @speaker.pic %>">
		<small class="text-muted">Try to pic a file with a <b>2:3</b> aspect ratio.</small>
	  </fieldset>

	  <fieldset class="form-group social">
		<input type="text" id="facebook" name="speaker[facebook_url]" class="form-control col-sm-10" placeholder="Facebook profile url" value="<%= @speaker.facebook_url %>">
	  </fieldset>

	  <fieldset class="form-group social">
		<input type="text" id="twitter" name="speaker[twitter_url]" class="form-control col-sm-10" placeholder="Twitter profile url" value="<%= @speaker.twitter_url %>">
	  </fieldset>

	  <fieldset class="form-group social">
		<input type="text" id="linkedin" name="speaker[linkedin_url]" class="form-control col-sm-10" placeholder="Linkedin profile url" value="<%= @speaker.linkedin_url %>">
	  </fieldset>

	  <fieldset class="form-group">
		<button id="submit" type="submit" class="btn btn-primary btn-right">Confirm Edits</button>
	  </fieldset>
	</form>
  </div>
</div>

app/views/admin/index.html.erb
<div id="index-page">

</div>

app/views/admin/new_speaker.html.erb
<div id="new-speaker">
	<div class="container">
	  <% flash.each do |key, value| %>
		  <div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>
	  <h1 class="section-title">Add a Speaker</h1>

	  <form action="<%= admin_create_speaker_url %>" method="post" class="new-speaker-form" enctype="multipart/form-data">

		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

		<fieldset class="form-group">
		  <label class="control-label" for="name">Name</label>
		  <input name="speaker[name]" type="text" id="name" class="form-control">
		</fieldset>

		<fieldset class="form-group">
		  <label class="control-label" for="name">Title</label>
		  <input name="speaker[title]" type="text" id="title" class="form-control">
		</fieldset>

		<fieldset class="form-group">
		  <label class="control-label" for="slug">Slug</label>
		  <input name="speaker[slug]" type="text" id="slug" class="form-control" placeholder="e.g. john_doe">
		  <small class="text-muted">This will be for the pretty URL. The speaker's profile will be at <b>/speaker/slug_here</b>.</small>
		</fieldset>

		<fieldset class="form-group">
		  <label class="control-label" for="bio">Bio</label>
		  <textarea name="speaker[bio]" id="bio" cols="30" rows="10" class="form-control"></textarea>
		  <small class="text-muted">You can use <a href="https://help.github.com/articles/markdown-basics/">markdown</a> here.</small>
		</fieldset>

		<fieldset class="form-group">
		  <label class="control-label" for="profile-pic">Profile picture</label>
		  <input type="file" class="form-control-file" name="speaker[pic]">
		  <small class="text-muted">Try to pic a file with a <b>2:3</b> aspect ratio.</small>
		</fieldset>

		<fieldset class="form-group social">
		  <input type="text" id="facebook" name="speaker[facebook_url]" class="form-control col-sm-10" placeholder="Facebook profile url">
		</fieldset>

		<fieldset class="form-group social">
		  <input type="text" id="twitter" name="speaker[twitter_url]" class="form-control col-sm-10" placeholder="Twitter profile url">
		</fieldset>

		<fieldset class="form-group social">
		  <input type="text" id="linkedin" name="speaker[linkedin_url]" class="form-control col-sm-10" placeholder="Linkedin profile url">
		</fieldset>

		<fieldset class="form-group">
		  <button id="submit" type="submit" class="btn btn-primary btn-right">Add Speaker</button>
		</fieldset>
	  </form>

	</div>
</div>

app/views/admin/show_speakers.html.erb
<div id="show-speakers">
	<div class="container">

	  <h1 class="section-title">Speakers <%= link_to '+', admin_new_speaker_path, class: 'add-speaker' %></h1>

	  	<% if @speakers %>
	  	<div class="row">
		  	<div class="col-sm-12">
			  <div class="table-responsive">
				<table class="table table-striped table-bordered speakers-table">
				  <thead>
				  <tr>
					<th class="number">#</th>
					<th class="name">Name</th>
					<th class="slug">Slug</th>
					<th class="view"></th>
					<th class="edit"></th>
					<th class="delete"></th>
				  </tr>
				  </thead>
				  <tbody>
				  <% @speakers.sort { |a,b| a.id <=> b.id }.each do |s| %>
					  <tr>
						<th class="number" scope="row"><%= s.id %></th>
						<td><%= s.name %></td>
						<td><%= s.slug %></td>
						<td class="view"><%= link_to '<i class="fa fa-eye"></i>'.html_safe, show_speaker_path(slug: s.slug) %></td>
						<td class="edit"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, admin_edit_speaker_path(slug: s.slug) %></td>
						<td class="delete confirm-action"><%= link_to '<i class="fa fa-times"></i>'.html_safe, admin_delete_speaker_path(slug: s.slug), method: :delete %></a></td>
					  </tr>
				  <% end %>
				  </tbody>
				</table>
			  </div>
			</div>
		</div>
		<% else %>
	  		<div class="no-speakers">
			  	<h1>No speakers found</h1>
			  	<h2 class="subtitle">Why don't you add some and then come back</h2>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_admin_nav.html.erb
<section id="top-nav" class="top-nav group <% if @nav_with_bg == true %>with-background<% end %>">
  <div class="container">
    <div class="top-nav__left-side">
	  <%= link_to 'REIFACON ADMIN', admin_root_path, class: 'top-nav__left-side__logo' %>
    </div>
    <div class="top-nav__right-side">
	  <% if user_signed_in? %>
      <nav class="top-nav__right-side__main-navigation">
        <ul>
          <li>
            <%= link_to 'Home', admin_root_path, class: 'hidden-md hidden-xs' %>
          </li>
          <li>
            <%= link_to 'Site Options', admin_site_options_path %>
          </li>
          <li>
            <%= link_to 'Speakers', admin_show_speakers_path %>
          <li>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'special' %>
          </li>
        </ul>
      </nav>
	  <% end %>
    </div>
  </div>
  <div id="menu-grabber"></div>
</section>

app/views/layouts/_footer.html.erb
<section id="questions">
    <h1>Questions?</h1>
    <div class="info">
      Feel free to email us at information@reifa.org<br />
      or call us at 619.665.3543
    </div>
</section>

<footer id="main-footer">
  <div class="container">
    <div class="row">
      <div class="hashtag col-md-3 col-sm-12">
        <a href="https://twitter.com/search?q=reifacon">#REIFACON</a>
      </div>
      <nav class="bottom-nav col-md-6 col-sm-12">
        <ul>
          <li><a href="about.html">About</a></li>
          <li><a href="agenda.html">Agenda</a></li>
          <li><a href="sponsors.html">Sponsors</a></li>
          <li><a class="special" href="https://realwealth.infusionsoft.com/app/orderForms/REIFACON15-Attendee" target="_blank">Register</a></li>
        </ul>
      </nav>
      <div class="social-links">
        <a class="facebook" href="https://www.facebook.com/reifacon/" target="_blank"></a>
        <a class="twitter" href="https://twitter.com/reifacon" target="_blank"></a>
        <a class="gplus" href="https://plus.google.com/+Reifacon_is_Here" target="_blank"></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<section id="top-nav" class="top-nav group <% if @nav_with_bg == true %>with-background<% end %>">
  <div class="container">
    <div class="top-nav__left-side">
      <a href="/" class="top-nav__left-side__logo">REIFACON</a>
    </div>
    <div class="top-nav__right-side">
      <nav class="top-nav__right-side__main-navigation">
        <ul>
          <li>
            <%= link_to 'Home', root_path, class: 'hidden-md hidden-xs' %>
          </li>
          <li>
            <%= link_to 'About', about_path %>
          </li>
          <li>
            <%= link_to 'Agenda', agenda_path %>
          </li>
          <li>
            <%= link_to 'Sponsors', sponsors_path %>
          </li>
          <li>
            <a class="special" href="https://realwealth.infusionsoft.com/app/orderForms/REIFACON15-Attendee" target="_blank">Register</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <div id="menu-grabber"></div>
</section>

app/views/layouts/admin.html.erb
<html lang="en">
	<head>
		<title>REIFACON 2016 - Los Angeles</title>
		<%= stylesheet_link_tag    'admin', media: 'all' %>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<%= javascript_include_tag 'admin' %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/admin_nav' %>
		<%= yield %>
		<%= render 'layouts/admin_footer' %>
	</body>
</html>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <title>REIFACON 2016 - <%= yield(:title) || 'Los Angeles' %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/speakers/show.html.erb
<div id="speaker-page">
  <div class="speaker container">
    <div class="left-side col-md-4 col-sm-12">
      <img class="profile-pic col-xs-8 col-xs-offset-2 col-sm-8 col-sm-offset-0 col-md-12 col-md-offset-0" src="<%= @speaker.pic.url %>" alt="<%= @speaker.name %> profile picture">
      <div class="social-links col-xs-12 col-sm-4 col-md-12">
        <% if @speaker.facebook_url.to_s != '' %>
            <a href="<%= @speaker.facebook_url %>" class="facebook"><i class="fa fa-facebook-square"></i></a>
        <% end %>
        <% if @speaker.twitter_url.to_s != '' %>
            <a href="<%= @speaker.twitter_url %>" class="twitter"><i class="fa fa-twitter-square"></i></a>
        <% end %>
        <% if @speaker.linkedin_url.to_s != '' %>
            <a href="<%= @speaker.linkedin_url %>" class="linkedin"><i class="fa fa-linkedin-square"></i></a>
        <% end %>
      </div>
    </div>
    <div class="right-side col-md-8 col-sm-12">
      <h1 class="name">
        <%= @speaker.name %>
      </h1>
      <h2 class="title">
        <%= @speaker.title %>
      </h2>
      <div class="bio">
        <%== markdown(@speaker.bio) %>
      </div>
    </div>
  </div>
</div>